<?php
$_product                       = $block->getProduct();
$_mediaDirectory                = $block->getMediadirectory();
$_productNumber                 = $_product->getSku();
$_arButtonForThisProductEnabled = $_product->getArbuttonEnable();
$_qrForThisProductEnabled       = $_product->getQrEnable();
$_arDeeplinkUrl                 = $_product->getArDeeplinkUrl();
$_overrideJourneyBaseUrl        = $_product->getJourneybaseurlOverride();
$_overrideArBaseUrl             = $_product->getArbaseurlOverride();
$_manualUrl                     = $_product->getManualUrl();
$_enableCompanyReference        = $_product->getCompanyrefEnable();
$userAgent = $block->getHttpUserAgent();
$isMobile = \Zend_Http_UserAgent_Mobile::match($userAgent, $_SERVER);
$_cwEnabled                   = $this->helper('ConfigWise\Configurator\Helper\Data')->getConfig('configwise/general/enable');
$_arButtonEnabled             = $this->helper('ConfigWise\Configurator\Helper\Data')->getConfig('configwise/ar_qr/enable_ar');
$_qrEnabled                   = $this->helper('ConfigWise\Configurator\Helper\Data')->getConfig('configwise/ar_qr/enable_qr');
$_deepLinkURL                 = $this->helper('ConfigWise\Configurator\Helper\Data')->getConfig('configwise/ar_qr/deeplinkurl');
$_arButtonText                = $this->helper('ConfigWise\Configurator\Helper\Data')->getConfig('configwise/ar_qr/text');
$_dynamicText                 = $this->helper('ConfigWise\Configurator\Helper\Data')->getConfig('configwise/ar_qr/dynamic_text');
$_referenceNumber             = $this->helper('ConfigWise\Configurator\Helper\Data')->getConfig('configwise/ar_qr/ref_num');
$_journeyBaseUrl              = $this->helper('ConfigWise\Configurator\Helper\Data')->getConfig('configwise/ar_qr/journey_base_url');
$_desktopImage                = $this->helper('ConfigWise\Configurator\Helper\Data')->getConfig('configwise/desktop_config/desktop_image');
$_displayQRCode               = $this->helper('ConfigWise\Configurator\Helper\Data')->getConfig('configwise/desktop_config/generated_qr_code');
$_instructionText             = $this->helper('ConfigWise\Configurator\Helper\Data')->getConfig('configwise/desktop_config/instruction_text');
$_captionText                 = $this->helper('ConfigWise\Configurator\Helper\Data')->getConfig('configwise/desktop_config/caption_text');
$_desktopFooterImageOne       = $this->helper('ConfigWise\Configurator\Helper\Data')->getConfig('configwise/desktop_config/configurable_first_image');
$_desktopFooterImageSecond    = $this->helper('ConfigWise\Configurator\Helper\Data')->getConfig('configwise/desktop_config/configurable_second_image');
$_configurableTitle           = $this->helper('ConfigWise\Configurator\Helper\Data')->getConfig('configwise/desktop_config/configurable_title');
$_configurableTitleColor      = $this->helper('ConfigWise\Configurator\Helper\Data')->getConfig('configwise/desktop_config/title_color');
$_configurableBgColor         = $this->helper('ConfigWise\Configurator\Helper\Data')->getConfig('configwise/desktop_config/background_color');
$_mobileButtonText            = $this->helper('ConfigWise\Configurator\Helper\Data')->getConfig('configwise/mobile_config/mobile_button_text');
$_mobileInstructionText       = $this->helper('ConfigWise\Configurator\Helper\Data')->getConfig('configwise/mobile_config/mobile_instruction');
$_mobileImage                 = $this->helper('ConfigWise\Configurator\Helper\Data')->getConfig('configwise/mobile_config/mobile_image');

$_url = '';
$_baseUrl = '';
if ($_arDeeplinkUrl == 1) { // SKU Link
    if ($_overrideArBaseUrl) {
        $_baseUrl = $_overrideArBaseUrl;
    } elseif ($_deepLinkURL) {
        $_baseUrl = $_deepLinkURL;
    }
    if ($_baseUrl) {
        if ($_enableCompanyReference && $_referenceNumber) {
            $_url = $_baseUrl . "?productNr=" . $_productNumber . "-" . $_referenceNumber . "&android_passive_deepview=false&ios_passive_deepview=false";
        } elseif (!$_enableCompanyReference) {
            $_url = $_baseUrl . "?productNr=" . $_productNumber . "&android_passive_deepview=false&ios_passive_deepview=false";
        }
    }

} elseif ($_arDeeplinkUrl == 2) { // Journey link
    if ($_overrideJourneyBaseUrl) {
        $_url = $_overrideJourneyBaseUrl . $_productNumber;
    } elseif ($_journeyBaseUrl) {
        $_url = $_journeyBaseUrl . $_productNumber;
    }
} elseif ($_arDeeplinkUrl == 3 && $_manualUrl) { // Manual Link
    $_url = $_manualUrl;
}

if ($_referenceNumber) {
    $_productNumber = $_productNumber . '-' . $_referenceNumber;
}
if ($_cwEnabled && $_arButtonEnabled && $_arButtonForThisProductEnabled && $_url) {
    if ($isMobile) { ?>

    <h3><a href="javascript:void(0)" id="pdp-chart"><?php echo $_mobileButtonText; ?></a> </h3>      
    <div id="mobile-popup-config" class="mobile-popup-config" style="display:none;">
      <div class="mobile-popup-config-image">
         <img src="<?php echo $_mediaDirectory.$_mobileImage;?>" alt="no-image">
      </div>
      <div class="mobile-popup-config-dec">
        <?php if (isset($_mobileInstructionText)): ?>
        <p><?php echo $_mobileInstructionText; ?></p>
        <?php endif; ?> 
        <a href="<?php echo $_url ;?>" class="btn action primary"><?php echo $_mobileButtonText;?></a>
      </div>
    </div>
        <?php
    }
}

if ($_cwEnabled && $_qrEnabled && $_qrForThisProductEnabled && $_url) {
    if ($isMobile) {
    } else { // Desktop
        ?>       
        <div id="ar-qr-h2c-gen" class="product-huis-section">
         <div class="product-huis-section-wrap">
          <?php if (isset($_desktopImage)): ?>
            <div class="section-top-image">
              <img src="<?php echo $_mediaDirectory.$_desktopImage;?>" alt="no-image">
            </div>
          <?php endif; ?>
          <div class="section-dec" style="background-color: <?php echo '#'.$_configurableBgColor; ?>">
           <?php if (isset($_dynamicText)): ?>
            <h3><?php echo $_dynamicText;?></a></h3>
          <?php endif; ?> 
          <div class="section-dec-qr-wrap">              
            <?php if ($_displayQRCode == 1): ?>
              <div class="section-dec-qr-code">
                <img src="<?php echo $this->getQr($_url, $_productNumber);?>" title="AR"/>
              </div>
                <?php
                $instance = \Magento\Framework\App\ObjectManager::getInstance();
                $product_id = $_product->getId();
                $productimages = [];
                $product = $instance ->create('Magento\Catalog\Model\Product')->load($product_id);
                $productimages = $product->getMediaGalleryImages();
                foreach ($productimages as $productimage) {
                    echo "<img src = ".$productimage['url']. " height=100 width=100  class='pdp-thumb-img'/>";
                }

                ?>
            <?php endif; ?>               
            <div class="section-dec-qr-dec">
              <?php if (isset($_configurableTitle)): ?>
                <h6 style="color: <?php echo '#'.$_configurableTitleColor; ?>">
                    <?php echo $_configurableTitle; ?></h6>
              <?php endif; ?> 
              <?php if (isset($_instructionText)): ?>
                <p><?php echo $_instructionText; ?></p>
              <?php endif; ?> 
              <?php if (isset($_captionText)): ?>
                <p><?php echo $_captionText; ?></p>
              <?php endif; ?> 
            </div>              
          </div>
          <div class="section-footer">
            <div class="section-footer-wrap">
              <?php if (isset($_desktopFooterImageOne)): ?>
                <img src="<?php echo $_mediaDirectory.$_desktopFooterImageOne; ?>">
              <?php endif; ?> 
              <?php if (isset($_desktopFooterImageSecond)): ?>
                <img src="<?php echo $_mediaDirectory.$_desktopFooterImageSecond; ?>">
              <?php endif; ?> 
            </div>
          </div>
        </div>
      </div>
    </div>        
        <?php
    }
}
?>
<script>
require(
    [
        'jquery',
        'Magento_Ui/js/modal/modal',
        'domReady!'
    ],
    function($, modal) {
        $(function() {
         $("body").on("click", "#pdp-chart", function(e) {
                var options = {
                    type: 'popup',
                    responsive: true,
                    innerScroll: true,
                    buttons: false
                };
                var popup = modal(options, $('#mobile-popup-config'));
                $("#mobile-popup-config").modal("openModal");
            });
        });
    }
);
</script>
<style type="text/css">
  .product-huis-section{max-width: 600px;width: 100%;display:block;}
  .product-huis-section .section-top-image{width: 100%;display: flex;align-items: center;}
  .product-huis-section .section-top-image img{width: 100%;}
  img.pdp-thumb-img {display: none;}  
  .product-huis-section .section-dec{padding: 10px 20px;box-sizing: border-box;}
  .product-huis-section .section-dec h3{font-weight: bold;font-size: 24px;line-height: 1.2;margin-bottom: 15px;color: #fff;margin-top: 0px;}
  .product-huis-section .section-dec-qr-wrap{display: flex;flex-wrap: wrap;color: #fff;}
  .product-huis-section .section-dec-qr-wrap .section-dec-qr-code{width: 100%;max-width: 150px;}
  .product-huis-section .section-dec-qr-wrap .section-dec-qr-dec{max-width: calc(100% - 150px);width: 100%;padding-left: 15px;box-sizing: border-box;}
  .product-huis-section .section-dec-qr-wrap h6{font-size: 16px;margin-bottom: 15px;line-height: 1.3;margin-top: 0px;}
  .product-huis-section .section-dec-qr-wrap p{font-size: 14px;line-height: 1.3;}
  .product-huis-section .section-footer{width: 100%%;}
  .product-huis-section .section-footer-wrap{display: flex;justify-content: flex-end;}
  .product-huis-section .section-footer-wrap img:not(:last-child){margin-right:15px;}
  .product-huis-section .section-footer-wrap img{max-width: 130px;}
  .mobile-popup-config .mobile-popup-config-image{width: 100%;display: flex;align-items: center;margin-bottom: 15px;}
  .mobile-popup-config .mobile-popup-config-image img{width: 100%;}
  .mobile-popup-config .mobile-popup-config-dec a{display:block;width: 100%;border-radius: 150px;background-color: #fb6e6c;color: #fff;font-weight: bold;font-size: 14px;text-align: center;border:none;} 
</style>

<script type="text/javascript">
    require(['jquery', 'html2canvas'], function($){
          html2canvas([document.getElementById('ar-qr-h2c-gen')], {
              onrendered: function(canvas) {
                 var imgdata = canvas.toDataURL('image/png');
                  $.ajax({
                      type: "POST",
                      url: "<?php echo $this->getBaseUrl() ?>configwise/index/save",
                      data: {imgdata:imgdata,id:"<?php echo $_product->getId() ?>"},
                      success : function(data)
                      {
                        window.location.href = data.redirect_url;
                      }
                  })
              }
          });
    });
</script>
